apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/git-branch: master
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2016-08-11T15:26:20Z
  labels:
    component: metrics-grafana
    container: docker
    group: metrics
    project: metrics-grafana
    provider: welshstew
    version: 1.0-SNAPSHOT
  name: metrics-grafana
  namespace: origin-metrics
spec:
  replicas: 1
  selector:
    component: metrics-grafana
    container: docker
    group: metrics
    project: metrics-grafana
    provider: welshstew
    version: 1.0-SNAPSHOT
  strategy:
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        component: metrics-grafana
        container: docker
        group: metrics
        project: metrics-grafana
        provider: welshstew
        version: 1.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: welshstew/hawkular-metrics-grafana:latest
        imagePullPolicy: Always
        name: metrics-grafana
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 400m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccount: grafana
      serviceAccountName: grafana
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange